language: objective-c

script:
  - xctool -workspace ProxyKit.xcworkspace -scheme ProxyKitTestsiOS -sdk iphonesimulator7.1 ONLY_ACTIVE_ARCH=NO test
  - xctool -workspace ProxyKit.xcworkspace -scheme ProxyKitTestsMac -sdk macosx10.9 ONLY_ACTIVE_ARCH=NO test