language: objective-c
osx_image: xcode7.2

script:
  - xctool -workspace ./Tests/iOS/ProxyKit.xcworkspace -scheme ProxyKitTestsiOS -sdk iphonesimulator test
#  - xctool -workspace ProxyKit.xcworkspace -scheme ProxyKitTestsMac -sdk macosx10.9 ONLY_ACTIVE_ARCH=NO test